teleop_params:
    num_joysticks: 2
    max_rot: 6.0
    max_rot_slow: 2.0
    min_speed: 0.0  # Smallest linear speed which get the robot moving at all
    max_speed: 3.0
    max_speed_slow: 0.75
    joystick_pow: 2
    rotation_pow: 3     #Scaling factors used in teleop_joystick_comp
    joystick_deadzone: 0.125
    drive_rate_limit_time: 1250
    rotate_rate_limit_time: 1250
    climber_align_angle: 3.14159265 # Intake facing DS wall
    trigger_threshold: 0.5
    stick_threshold: 0.5
    button_move_speed: 0.6
    bottom_position_angle: -110.0
    middle_position_angle: -0.0
    top_position_angle: -200.0

    #teleop_diagnostics_params:
