teleop_params:
    num_joysticks: 2
    max_rot: 6.0
    max_rot_slow: 3.0
    min_speed: 0.0  # Smallest linear speed which get the robot moving at all
    max_speed: 3.0
    max_speed_slow: 1.5
    joystick_pow: 3
    rotation_pow: 4     #Scaling factors used in teleop_joystick_comp
    joystick_deadzone: 0.1
    drive_rate_limit_time: 1000
    rotate_rate_limit_time: 1000
    climber_align_angle: 3.14159265 # Intake facing DS wall
    climber_time_lock: 30
    trigger_threshold: 0.5
    stick_threshold: 0.5

teleop_diagnostics_params:
