#!/bin/bash

dev_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
dev_dir="$( dirname "$dev_dir" )"

set -e
set -o pipefail

docker run "$@" -it --net=host -v  /tmp/.X11-unix:/tmp/.X11-unix \
 -v $HOME/2022RobotCode:/home/ubuntu/2022RobotCode \
 -e DISPLAY=$DISPLAY -e NVIDIA_DRIVER_CAPABILITIES=all --privileged --user ubuntu 858968ed7df1 /bin/bash
