swerve_drive_controller:
    steering_joint_bl:
        offset: 1.32843
    steering_joint_br:
        offset: -2.4375
    steering_joint_fl:
        offset: 5.13884
    steering_joint_fr:
        offset: 2.66759
