swerve_drive_controller:
    steering_joint_bl:
        offset: -3.96994
    steering_joint_br:
        offset: 3.93313
    steering_joint_fl:
        offset: -1.01856
    steering_joint_fr:
        offset: -3.44532
