# 2022 TODO Set correct values for robot TODO TODO    TODO TODO  TODO TODO
swerve_drive_controller:
    type:       talon_swerve_drive_controller/TalonSwerveDriveController

    speed: ['speed_joint_fl', 'speed_joint_fr', 'speed_joint_bl', 'speed_joint_br']
    steering: ['steering_joint_fl', 'steering_joint_fr', 'steering_joint_bl', 'steering_joint_br']
    publish_cmd: True
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    wheel_radius: 0.050 # m
    cmd_vel_timout: 0.5
    max_speed: 5.75 # TODO
    max_accel: 1.8 # TODO
    max_brake_accel: 2.5 # TODO
    ang_accel_conv: 2.0
    max_rotational_vel: 10 # TODO

    f_s: 0.0175
    f_a: 0.005 #use torque curve instead? TODO: FIX
    f_v: 0.00315528

    #TODO: FIX BELOW!!!!
    f_s_s: 0.05
    f_s_v: 0.07

    #consider adding stuff for the steering wheels too
    mass: 70 # TODO 2022 Update
    motor_free_speed: 5840
    motor_stall_torque: 1.4
    motor_quantity: 4
    invert_wheel_angle: False
    ratio_encoder_to_rotations: 0.148148148 # Test me, will show up in odom results
    ratio_motor_to_rotations: 1 # TODO?
    ratio_motor_to_steering: 1 # TODO?
    encoder_drive_get_V_units: 1
    encoder_drive_set_V_units: 1
    encoder_drive_get_P_units: 1
    encoder_drive_set_P_units: 1
    encoder_steering_get_units: 1
    encoder_steering_set_units: 1

    wheel_coords: [[-0.27305, 0.27305], [0.27305, 0.27305], [-0.27305, -0.27305], [0.27305, -0.27305]]

    cmd_vel_timeout: 0.5 # we test this separately, give plenty for the other tests
    speed_joint_fl:
        joint: fl_drive #fix pid
        close_loop_values:
            - {p: 0.15, i: 0.0, d: 1.0, f: 0.043, i_zone: 0.0}
        sensor_phase: true
        invert_output: false
        feedback_type: IntegratedSensor
        voltage_compensation_enable: True
        current_limit_continuous_amps: 20
        closed_loop_ramp: 0.25
        current_limit_enable: True
        dynamic_reconfigure: True
        neutral_mode: "Brake"
        status_1_general_period: 100
        status_2_feedback0_period: 100
        #status_1_general_period: 10
        #status_2_feedback0_period: 20
        status_3_quadrature_period: 250
        #status_4_aintempvbat_period: 160
        #status_6_misc_period: 0
        #status_7_commstatus_period: 0
        status_8_pulsewidth_period: 250
        status_9_motprofbuffer_period: 250
        status_10_motionmagic_period: 250
        #status_11_uartgadgeteer_period: 250
        #status_12_feedback1_period: 250
        #status_13_base_pidf0_period: 160
        #status_14_turn_pidf1_period: 250
        status_15_firmwareapistatus_period: 250
        #status_17_targets1_period: 0
        #status_17_brushless_current_period: 0
        neutral_deadband: 0.01
    speed_joint_fr:
        joint: fr_drive #fix pid
        close_loop_values:
            - {p: 0.15, i: 0.0, d: 1.0, f: 0.043, i_zone: 0.0}
        sensor_phase: true
        invert_output: false
        feedback_type: IntegratedSensor
        voltage_compensation_enable: True
        current_limit_continuous_amps: 20
        current_limit_enable: True
        dynamic_reconfigure: True
        neutral_mode: "Brake"
        neutral_deadband: 0.01
        closed_loop_ramp: 0.25
        status_1_general_period: 100
        status_2_feedback0_period: 100
        #status_1_general_period: 10
        #status_2_feedback0_period: 20
        status_3_quadrature_period: 250
        #status_4_aintempvbat_period: 160
        #status_6_misc_period: 0
        #status_7_commstatus_period: 0
        status_8_pulsewidth_period: 250
        status_9_motprofbuffer_period: 250
        status_10_motionmagic_period: 250
        #status_11_uartgadgeteer_period: 250
        #status_12_feedback1_period: 250
        #status_13_base_pidf0_period: 160
        #status_14_turn_pidf1_period: 250
        status_15_firmwareapistatus_period: 250
        #status_17_targets1_period: 0
        #status_17_brushless_current_period: 0
    speed_joint_bl:
        joint: bl_drive #fix pid
        close_loop_values:
            - {p: 0.15, i: 0.0, d: 1.0, f: 0.043, i_zone: 0.0}
        sensor_phase: true
        feedback_type: IntegratedSensor
        sensor_phase: true
        invert_output: false
        voltage_compensation_enable: True
        current_limit_continuous_amps: 20
        current_limit_enable: True
        dynamic_reconfigure: True
        neutral_mode: "Brake"
        neutral_deadband: 0.01
        closed_loop_ramp: 0.25
        status_1_general_period: 100
        status_2_feedback0_period: 100
        #status_1_general_period: 10
        #status_2_feedback0_period: 20
        status_3_quadrature_period: 250
        #status_4_aintempvbat_period: 160
        #status_6_misc_period: 0
        #status_7_commstatus_period: 0
        status_8_pulsewidth_period: 250
        status_9_motprofbuffer_period: 250
        status_10_motionmagic_period: 250
        #status_11_uartgadgeteer_period: 250
        #status_12_feedback1_period: 250
        #status_13_base_pidf0_period: 160
        #status_14_turn_pidf1_period: 250
        status_15_firmwareapistatus_period: 250
        #status_17_targets1_period: 0
        #status_17_brushless_current_period: 0
    speed_joint_br:
        joint: br_drive #fix pid
        close_loop_values:
            - {p: 0.15, i: 0.0, d: 1.0, f: 0.043, i_zone: 0.0}
        sensor_phase: True
        invert_output: false
        feedback_type: IntegratedSensor
        voltage_compensation_enable: True
        current_limit_continuous_amps: 20
        current_limit_enable: True
        dynamic_reconfigure: True
        neutral_mode: "Brake"
        neutral_deadband: 0.01
        closed_loop_ramp: 0.25
        status_1_general_period: 100
        status_2_feedback0_period: 100
        #status_1_general_period: 10
        #status_2_feedback0_period: 20
        status_3_quadrature_period: 250
        #status_4_aintempvbat_period: 160
        #status_6_misc_period: 0
        #status_7_commstatus_period: 0
        status_8_pulsewidth_period: 250
        status_9_motprofbuffer_period: 250
        status_10_motionmagic_period: 250
        #status_11_uartgadgeteer_period: 250
        #status_12_feedback1_period: 250
        #status_13_base_pidf0_period: 160
        #status_14_turn_pidf1_period: 250
        status_15_firmwareapistatus_period: 250
        #status_17_targets1_period: 0
        #status_17_brushless_current_period: 0
    steering_joint_fl:
        joint: fl_angle
        feedback_type: RemoteSensor0
        remote_feedback_filter0: CANCoder
        remote_feedback_device_id0: 11
        close_loop_values:
            - {p: 2.5, i: 0.000, d: 4.0, f: 0.28, i_zone: 0}
        invert_output: false
        sensor_phase: false
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 45
        motion_acceleration: 153.3
        voltage_compensation_enable: true
        dynamic_reconfigure: True
        status_1_general_period: 100
        status_2_feedback0_period: 100
        #status_1_general_period: 10
        #status_2_feedback0_period: 20
        status_3_quadrature_period: 250
        #status_4_aintempvbat_period: 160
        #status_6_misc_period: 0
        #status_7_commstatus_period: 0
        status_8_pulsewidth_period: 250
        status_9_motprofbuffer_period: 250
        #status_10_motionmagic_period: 160
        #status_11_uartgadgeteer_period: 250
        #status_12_feedback1_period: 250
        #status_13_base_pidf0_period: 160
        #status_14_turn_pidf1_period: 250
        status_15_firmwareapistatus_period: 250
        #status_17_targets1_period: 0
        #status_17_brushless_current_period: 0
    steering_joint_fr:
        joint: fr_angle
        feedback_type: RemoteSensor0
        remote_feedback_filter0: CANCoder
        remote_feedback_device_id0: 12
        close_loop_values:
            - {p: 2.5, i: 0.000, d: 4.0, f: 0.28, i_zone: 0}
        invert_output: false
        sensor_phase: false
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 45
        motion_acceleration: 153.3
        voltage_compensation_enable: true
        dynamic_reconfigure: True
        status_1_general_period: 100
        status_2_feedback0_period: 100
        #status_1_general_period: 10
        #status_2_feedback0_period: 20
        status_3_quadrature_period: 250
        #status_4_aintempvbat_period: 160
        #status_6_misc_period: 0
        #status_7_commstatus_period: 0
        status_8_pulsewidth_period: 250
        status_9_motprofbuffer_period: 250
        #status_10_motionmagic_period: 160
        #status_11_uartgadgeteer_period: 250
        #status_12_feedback1_period: 250
        #status_13_base_pidf0_period: 160
        #status_14_turn_pidf1_period: 250
        status_15_firmwareapistatus_period: 250
        #status_17_targets1_period: 0
        #status_17_brushless_current_period: 0
    steering_joint_br:
        joint: br_angle
        feedback_type: RemoteSensor0
        remote_feedback_filter0: CANCoder
        remote_feedback_device_id0: 14
        close_loop_values:
            - {p: 2.5, i: 0.000, d: 4.0, f: 0.28, i_zone: 0}
        invert_output: false
        sensor_phase: false
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 45
        motion_acceleration: 153.3
        voltage_compensation_enable: true
        dynamic_reconfigure: True
        status_1_general_period: 100
        status_2_feedback0_period: 100
        #status_1_general_period: 10
        #status_2_feedback0_period: 20
        status_3_quadrature_period: 250
        #status_4_aintempvbat_period: 160
        #status_6_misc_period: 0
        #status_7_commstatus_period: 0
        status_8_pulsewidth_period: 250
        status_9_motprofbuffer_period: 250
        #status_10_motionmagic_period: 160
        #status_11_uartgadgeteer_period: 250
        #status_12_feedback1_period: 250
        #status_13_base_pidf0_period: 160
        #status_14_turn_pidf1_period: 250
        status_15_firmwareapistatus_period: 250
        #status_17_targets1_period: 0
        #status_17_brushless_current_period: 0
    steering_joint_bl:
        joint: bl_angle
        feedback_type: RemoteSensor0
        remote_feedback_filter0: CANCoder
        remote_feedback_device_id0: 13
        close_loop_values:
            - {p: 2.5, i: 0.000, d: 4.0, f: 0.28, i_zone: 0}
        invert_output: false
        sensor_phase: false
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 45
        motion_acceleration: 153.3
        voltage_compensation_enable: true
        dynamic_reconfigure: True
        status_1_general_period: 100
        status_2_feedback0_period: 100
        #status_1_general_period: 10
        #status_2_feedback0_period: 20
        status_3_quadrature_period: 250
        #status_4_aintempvbat_period: 160
        #status_6_misc_period: 0
        #status_7_commstatus_period: 0
        status_8_pulsewidth_period: 250
        status_9_motprofbuffer_period: 250
        #status_10_motionmagic_period: 160
        #status_11_uartgadgeteer_period: 250
        #status_12_feedback1_period: 250
        #status_13_base_pidf0_period: 160
        #status_14_turn_pidf1_period: 250
        status_15_firmwareapistatus_period: 250
        #status_17_targets1_period: 0
        #status_17_brushless_current_period: 0
