full_extend_height_ground: 0.9 # 0.9 meters
full_extend_height_air: 0.75 # 0.75 meters
semi_extend_height: 0.2 # 0.2 meters
static_hook_distance_above_rung: 0.09 # 8-10 cm
get_to_zero_percent_output: -0.08 # 0.08 meters/second down
