full_extend_height_ground: 0.89 # meters
full_extend_height_air: 0.75 # 0.75 meters
static_hook_release_height: 0.5 # 0.5 meters
static_hook_initial_distance: 0.05 # 5 cm, wait for sensors, then move up to `static_hook_distance_above_rung`
static_hook_distance_above_rung: 0.09 # 9 cm
get_to_zero_percent_output: -0.16 # 0.16 meters/second down
imbalance_timeout: 10000.0
falcons_for_finale: ["indexer_straight_motor", "indexer_arc_motor", "shooter_leader", "fl_drive", "fr_drive", "bl_drive", "br_drive"]
finale_track: "/home/ubuntu/2022RobotCode/zebROS_ws/src/behaviors/chirp/mario.chrp"
