full_extend_height_ground: 0.86 # meters
full_extend_height_air: 0.75 # 0.75 meters
static_hook_release_height: 0.5 # 0.5 meters
static_hook_distance_above_rung: 0.09 # 9 cm
get_to_zero_percent_output: -0.16 # 0.16 meters/second down
imbalance_timeout: 10000.0
