# Points *must* end in .0 if integers
endpoints:
  - {x: 12.0, y: 6.0, z: 0.0, rot: 45.0}
  - {x: 4.0, y: 3.0, z: 0.0, rot: 0.0}
intake_frame_id: "intake"
secondary_max_objects: 11
secondary_max_distance: 1.0
secondary_frame_id: "base_link" # eventually roller or something, probably
min_radius: 1.0
