noise_delta_t: 1.0
map_frame_id: 'map'
odom_frame_id: 'zed_objdet_odom'
field_dims:
  x_min: -6.0
  x_max: 6.0
  y_min: -6.0
  y_max: 6.0

init_dims:
  x_min: -6.0
  x_max: 6.0
  y_min: -6.0
  y_max: 6.0

num_particles: 200

noise_stdev:
  position: 0.025
  rotation: 0.001

camera_sigmas: [ 0.500, 0.500 ]

beacons:
  - [0.0, -0.24, "51"]
  - [0.0, -0.24, "17"]
  - [-0.68, 1.55, "3"]