noise_delta_t: 1.0
map_frame_id: 'map'
odom_frame_id: 'zed_objdet_odom'

field_dims:
  x_min: -2.0
  x_max: 9.144
  y_min: -2.0
  y_max: 4.572

init_dims:
  x_min: 0.0
  x_max: 1.524
  y_min: 0.0
  y_max: 3.048

num_particles: 200

noise_stdev:
  position: 0.025
  rotation: 0.001

camera_sigmas: [ 0.500, 0.500 ]

beacons:
  - [-1.72, -0.2, "100"]
  - [-1.72, 0.48, "600"]
  - [-1.72, 1.145, "200"]
  - [-1.72, 1.638, "400"]
  - [-1.72, 2.263, "500"]
  - [-1.72, 3.103, "300"]
