noise_delta_t: 1.0

field_dims:
  x_min: 0.0
  x_max: 4.0
  y_min: 0.0
  y_max: 4.0

init_dims:
  x_min: 0.0
  x_max: 4.0
  y_min: 0.0
  y_max: 4.0

num_particles: 200

noise_stdev:
  position: 0.025
  rotation: 0.001

camera_sigmas: [ 0.500, 0.500 ]

beacons:
  - [3.0, 3.0, "loading_bay"]
  - [3.0, 2.0, "loading_bay"]
  - [4.0, 1.0, "loading_bay"]
